deploy: Edited dist path

diff --git a/.github/workflows/deploy-acocunt-service.yml b/.github/workflows/deploy-acocunt-service.yml
--- a/.github/workflows/deploy-acocunt-service.yml
+++ b/.github/workflows/deploy-acocunt-service.yml
@@ -44,12 +44,12 @@ jobs:
           ls -al
 
           echo "Contents of dist/apps/account-service:"
-          ls -al ./dist/apps/account-service || echo "dist/apps/account-service not found"
+          ls -al dist/apps/account-service || echo "dist/apps/account-service not found"
 
           echo "Now copying files..."
 
-          cp -r ./dist/apps/account-service/src/* .
-          cp -r ./dist/libs/* . || true
+          cp -r dist/apps/account-service/src/* .
+          cp -r dist/libs/* . || true
 
           # Overwrite package.json with production-only
           node -p "
